[Feature] Use the last modified time of the project file to return document cache
3liz/qgis-server-wmts-cache-plugin pull request #3
Opened 2021-05-21 19:50 UTC by rldhont

If the time of most recent content modification of document cached is greater than the last modified time of the project
file as returned by the file system or other project storage then the cached is returned else the cached document is removed.

* Funded by Ifremer

2021-05-25 08:15 UTC, dmarteau requested changes

2021-05-25 08:46 UTC, rldhont commented on wmtsCacheServer/cachefilter.py
> +                if dcDateTime > pDateTime:
@dmarteau in `CacheHelper` or in `DiskCacheFilter` ?

If I implement it in `CacheHelper`, I need to change the API.

2021-05-25 09:24 UTC, rldhont commented on wmtsCacheServer/cachefilter.py
> +                if dcDateTime > pDateTime:
add `DateTime` in `CacheHelper`

2021-05-25 16:16 UTC, rldhont commented on wmtsCacheServer/cachefilter.py
> +                if dcDateTime > pDateTime:
Changes done, ready for review

2021-05-27 10:21 UTC, dmarteau reviewed
LGTM

2021-05-27 10:21 UTC, dmarteau approved these changes

2021-05-27 11:20 UTC, merged